### ISSUE TITLE
Map skin still not working (1.9.0.0.3101)

### ISSUE THREAD

**Issue by panther2** [triplea-maps/napoleonic_empires-topographical_map_skin#2]
triplea.engine.version.bin:1.9
Loading map: napoleonic_empire, from: C:\Users\User\triplea\downloadedMaps\napoleonic_empire-master.zip
Loading map: napoleonic_empire, from: C:\Users\User\triplea\downloadedMaps\napoleonic_empire-master.zip
Loading map: napoleonic_empire_map_skin-master.zip, from: C:\Users\User\triplea\downloadedMaps\napoleonic_empire_map_skin-master.zip
Error Changing Map Skin2
java.lang.IllegalStateException: Error in resource loading. Unable to load expected resource: polygons.txt, the error is that either we did not find the correct path to load. Check the resource loader to make sure the map zip or dir was added. Failing that, the path in this error message should be available relative to the map folder, or relative to the root of the map zip
    at games.strategy.triplea.ui.mapdata.MapData.<init>(MapData.java:155)
    at games.strategy.triplea.ui.UIContext.internalSetMapDir(UIContext.java:77)
    at games.strategy.triplea.ui.AbstractUIContext.setMapDir(AbstractUIContext.java:123)
    at games.strategy.triplea.ui.TripleAFrame.updateMap(TripleAFrame.java:2082)
    at games.strategy.triplea.ui.menubar.ViewMenu.lambda$addMapSkinsMenu$666(ViewMenu.java:295)
    at javax.swing.AbstractButton.fireActionPerformed(Unknown Source)
    at javax.swing.AbstractButton$Handler.actionPerformed(Unknown Source)
    at javax.swing.DefaultButtonModel.fireActionPerformed(Unknown Source)
    at javax.swing.JToggleButton$ToggleButtonModel.setPressed(Unknown Source)
    at javax.swing.AbstractButton.doClick(Unknown Source)
    at javax.swing.plaf.basic.BasicMenuItemUI.doClick(Unknown Source)
    at javax.swing.plaf.basic.BasicMenuItemUI$Handler.mouseReleased(Unknown Source)
    at java.awt.AWTEventMulticaster.mouseReleased(Unknown Source)
    at java.awt.Component.processMouseEvent(Unknown Source)
    at javax.swing.JComponent.processMouseEvent(Unknown Source)
    at java.awt.Component.processEvent(Unknown Source)
    at java.awt.Container.processEvent(Unknown Source)
    at java.awt.Component.dispatchEventImpl(Unknown Source)
    at java.awt.Container.dispatchEventImpl(Unknown Source)
    at java.awt.Component.dispatchEvent(Unknown Source)
    at java.awt.LightweightDispatcher.retargetMouseEvent(Unknown Source)
    at java.awt.LightweightDispatcher.processMouseEvent(Unknown Source)
    at java.awt.LightweightDispatcher.dispatchEvent(Unknown Source)
    at java.awt.Container.dispatchEventImpl(Unknown Source)
    at java.awt.Window.dispatchEventImpl(Unknown Source)
    at java.awt.Component.dispatchEvent(Unknown Source)
    at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
    at java.awt.EventQueue.access$500(Unknown Source)
    at java.awt.EventQueue$3.run(Unknown Source)
    at java.awt.EventQueue$3.run(Unknown Source)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
    at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
    at java.awt.EventQueue$4.run(Unknown Source)
    at java.awt.EventQueue$4.run(Unknown Source)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
    at java.awt.EventQueue.dispatchEvent(Unknown Source)
    at games.strategy.engine.framework.GameRunner$1.dispatchEvent(GameRunner.java:353)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
    at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
    at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
    at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
    at java.awt.EventDispatchThread.run(Unknown Source)

**Comment by DanVanAtta** [comment]
Should be fixed after: https://github.com/triplea-game/triplea/pull/1205 is merged

**Comment by panther2** [comment]
Confirmed. Works fine with 3106, thanks.
